services:
  - type: static
    name: curebot-frontend
    env: static
    buildCommand: "npm ci && npm run build"
    publishPath: "dist"
    branch: main
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    buildFilter:
      paths:
        - "**/*"
